# .gitlab-ci.yml
stages:
  - build
  - test

variables:
  GO_VERSION: "1.24"

before_script:
  - echo "Using Go version $GO_VERSION"
  - apt-get update -qq && apt-get install -y curl git
  - curl -sSL "https://golang.org/dl/go$GO_VERSION.linux-amd64.tar.gz" | tar -C /usr/local -xz
  - export PATH="/usr/local/go/bin:$PATH"
  - go version
  - go mod tidy

build:
  stage: build
  script:
    - go build -v .

test:
  stage: test
  script:
    - go test -v ./...